/*This file was generated by NativeWind. Do not edit!*/
const {
  NativeWindStyleSheet: _NativeWindStyleSheet
} = require("nativewind");
_NativeWindStyleSheet.create({
  styles: {
    "*": {
      "borderTopWidth": 0,
      "borderRightWidth": 0,
      "borderBottomWidth": 0,
      "borderLeftWidth": 0,
      "borderStyle": "solid",
      "borderTopColor": "#e5e7eb",
      "borderRightColor": "#e5e7eb",
      "borderBottomColor": "#e5e7eb",
      "borderLeftColor": "#e5e7eb"
    },
    "": {
      "borderTopWidth": 0,
      "borderRightWidth": 0,
      "borderBottomWidth": 0,
      "borderLeftWidth": 0,
      "borderStyle": "solid",
      "borderTopColor": "#e5e7eb",
      "borderRightColor": "#e5e7eb",
      "borderBottomColor": "#e5e7eb",
      "borderLeftColor": "#e5e7eb"
    },
    "html": {
      "lineHeight": 1.5,
      "fontFamily": "ui-sans-serif"
    },
    "body": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "hr": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "abbr:where([title])": {
      "textDecorationLine": "underline",
      "textDecorationColor": "black",
      "textDecorationStyle": "dotted"
    },
    "code": {
      "fontFamily": "ui-monospace",
      "fontSize": "1em"
    },
    "kbd": {
      "fontFamily": "ui-monospace",
      "fontSize": "1em"
    },
    "samp": {
      "fontFamily": "ui-monospace",
      "fontSize": "1em"
    },
    "pre": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "small": {
      "fontSize": "80%"
    },
    "sub": {
      "fontSize": "75%",
      "lineHeight": 0,
      "position": "relative"
    },
    "sup": {
      "fontSize": "75%",
      "lineHeight": 0,
      "position": "relative"
    },
    "button": {
      "backgroundColor": "transparent"
    },
    "input": {
      "opacity": 1,
      "color": "#9ca3af"
    },
    "optgroup": {
      "fontFamily": "inherit",
      "fontSize": "100%",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "select": {
      "textTransform": "none"
    },
    "textarea": {
      "opacity": 1,
      "color": "#9ca3af"
    },
    "[type='button']": {
      "backgroundColor": "transparent"
    },
    "[type='reset']": {
      "backgroundColor": "transparent"
    },
    "[type='submit']": {
      "backgroundColor": "transparent"
    },
    ":-moz-ui-invalid": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "black",
      "shadowOpacity": 1
    },
    "blockquote": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "dl": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "dd": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h1": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h2": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h3": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h4": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h5": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h6": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "figure": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "p": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "fieldset": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "legend": {
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "ol": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "ul": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "menu": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "img": {
      "maxWidth": "100%"
    },
    "video": {
      "maxWidth": "100%"
    },
    "[hidden]": {
      "display": "none"
    },
    "shadow-sm@0": {
      "elevation": 1.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-sm@1": {
      "shadowOffset": {
        "width": 0,
        "height": 1
      },
      "shadowRadius": 2,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-sm@2": {
      "shadowOffset": {
        "width": 0,
        "height": 1
      },
      "shadowRadius": 2,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "absolute": {
      "position": "absolute"
    },
    "relative": {
      "position": "relative"
    },
    "top-7": {
      "top": 28
    },
    "left-4": {
      "left": 16
    },
    "right-4": {
      "right": 16
    },
    "left-0": {
      "left": 0
    },
    "right-0": {
      "right": 0
    },
    "top-[220px]": {
      "top": 220
    },
    "z-10": {
      "zIndex": 10
    },
    "my-1": {
      "marginTop": 4,
      "marginBottom": 4
    },
    "mx-4": {
      "marginLeft": 16,
      "marginRight": 16
    },
    "my-2": {
      "marginTop": 8,
      "marginBottom": 8
    },
    "my-4": {
      "marginTop": 16,
      "marginBottom": 16
    },
    "my-0.5": {
      "marginTop": 2,
      "marginBottom": 2
    },
    "my-0": {
      "marginTop": 0,
      "marginBottom": 0
    },
    "mb-2": {
      "marginBottom": 8
    },
    "mr-2": {
      "marginRight": 8
    },
    "ml-4": {
      "marginLeft": 16
    },
    "mt-6": {
      "marginTop": 24
    },
    "mt-4": {
      "marginTop": 16
    },
    "flex": {
      "display": "flex"
    },
    "h-[50px]": {
      "height": 50
    },
    "h-[100px]": {
      "height": 100
    },
    "h-full": {
      "height": "100%"
    },
    "h-16": {
      "height": 64
    },
    "h-[250px]": {
      "height": 250
    },
    "h-24": {
      "height": 96
    },
    "h-[200px]": {
      "height": 200
    },
    "min-h-[44px]": {
      "minHeight": 44
    },
    "w-[50px]": {
      "width": 50
    },
    "w-full": {
      "width": "100%"
    },
    "w-[100px]": {
      "width": 100
    },
    "w-[220px]": {
      "width": 220
    },
    "w-24": {
      "width": 96
    },
    "w-[200px]": {
      "width": 200
    },
    "w-20": {
      "width": 80
    },
    "flex-1": {
      "flexGrow": 1,
      "flexShrink": 1,
      "flexBasis": "0%"
    },
    "flex-row": {
      "flexDirection": "row"
    },
    "flex-row-reverse": {
      "flexDirection": "row-reverse"
    },
    "flex-col": {
      "flexDirection": "column"
    },
    "flex-wrap": {
      "flexWrap": "wrap"
    },
    "items-center": {
      "alignItems": "center"
    },
    "justify-center": {
      "justifyContent": "center"
    },
    "justify-between": {
      "justifyContent": "space-between"
    },
    "overflow-hidden": {
      "overflow": "hidden"
    },
    "rounded-full": {
      "borderTopLeftRadius": 9999,
      "borderTopRightRadius": 9999,
      "borderBottomRightRadius": 9999,
      "borderBottomLeftRadius": 9999
    },
    "rounded": {
      "borderTopLeftRadius": 4,
      "borderTopRightRadius": 4,
      "borderBottomRightRadius": 4,
      "borderBottomLeftRadius": 4
    },
    "rounded-md": {
      "borderTopLeftRadius": 6,
      "borderTopRightRadius": 6,
      "borderBottomRightRadius": 6,
      "borderBottomLeftRadius": 6
    },
    "rounded-lg": {
      "borderTopLeftRadius": 8,
      "borderTopRightRadius": 8,
      "borderBottomRightRadius": 8,
      "borderBottomLeftRadius": 8
    },
    "rounded-xl": {
      "borderTopLeftRadius": 12,
      "borderTopRightRadius": 12,
      "borderBottomRightRadius": 12,
      "borderBottomLeftRadius": 12
    },
    "border-2": {
      "borderTopWidth": 2,
      "borderRightWidth": 2,
      "borderBottomWidth": 2,
      "borderLeftWidth": 2
    },
    "border-r-2": {
      "borderRightWidth": 2
    },
    "border-l-2": {
      "borderLeftWidth": 2
    },
    "border-slate-300": {
      "borderTopColor": "#cbd5e1",
      "borderRightColor": "#cbd5e1",
      "borderBottomColor": "#cbd5e1",
      "borderLeftColor": "#cbd5e1"
    },
    "border-purple-400": {
      "borderTopColor": "#c084fc",
      "borderRightColor": "#c084fc",
      "borderBottomColor": "#c084fc",
      "borderLeftColor": "#c084fc"
    },
    "border-slate-200": {
      "borderTopColor": "#e2e8f0",
      "borderRightColor": "#e2e8f0",
      "borderBottomColor": "#e2e8f0",
      "borderLeftColor": "#e2e8f0"
    },
    "bg-slate-800": {
      "backgroundColor": "#1e293b"
    },
    "bg-slate-600": {
      "backgroundColor": "#475569"
    },
    "bg-slate-700": {
      "backgroundColor": "#334155"
    },
    "bg-sky-500": {
      "backgroundColor": "#0ea5e9"
    },
    "bg-rose-200": {
      "backgroundColor": "#fecdd3"
    },
    "bg-slate-300": {
      "backgroundColor": "#cbd5e1"
    },
    "bg-[#5046E4]": {
      "backgroundColor": "#5046E4"
    },
    "bg-purple-800": {
      "backgroundColor": "#6b21a8"
    },
    "bg-blue-200": {
      "backgroundColor": "#bfdbfe"
    },
    "bg-black": {
      "backgroundColor": "#000"
    },
    "bg-blue-800": {
      "backgroundColor": "#1e40af"
    },
    "bg-gray-800": {
      "backgroundColor": "#1f2937"
    },
    "bg-pink-500": {
      "backgroundColor": "#ec4899"
    },
    "bg-blue-500": {
      "backgroundColor": "#3b82f6"
    },
    "bg-emerald-500": {
      "backgroundColor": "#10b981"
    },
    "bg-purple-400": {
      "backgroundColor": "#c084fc"
    },
    "bg-orange-400": {
      "backgroundColor": "#fb923c"
    },
    "bg-fuchsia-600": {
      "backgroundColor": "#c026d3"
    },
    "bg-red-600": {
      "backgroundColor": "#dc2626"
    },
    "p-4": {
      "paddingTop": 16,
      "paddingRight": 16,
      "paddingBottom": 16,
      "paddingLeft": 16
    },
    "p-8": {
      "paddingTop": 32,
      "paddingRight": 32,
      "paddingBottom": 32,
      "paddingLeft": 32
    },
    "p-3": {
      "paddingTop": 12,
      "paddingRight": 12,
      "paddingBottom": 12,
      "paddingLeft": 12
    },
    "px-3": {
      "paddingLeft": 12,
      "paddingRight": 12
    },
    "px-0": {
      "paddingLeft": 0,
      "paddingRight": 0
    },
    "px-4": {
      "paddingLeft": 16,
      "paddingRight": 16
    },
    "py-2": {
      "paddingTop": 8,
      "paddingBottom": 8
    },
    "pt-2": {
      "paddingTop": 8
    },
    "pl-1": {
      "paddingLeft": 4
    },
    "pr-3": {
      "paddingRight": 12
    },
    "pl-1.5": {
      "paddingLeft": 6
    },
    "pr-4": {
      "paddingRight": 16
    },
    "pt-3": {
      "paddingTop": 12
    },
    "pl-[90px]": {
      "paddingLeft": 90
    },
    "pr-16": {
      "paddingRight": 64
    },
    "pl-4": {
      "paddingLeft": 16
    },
    "pt-4": {
      "paddingTop": 16
    },
    "pb-3": {
      "paddingBottom": 12
    },
    "text-center": {
      "textAlign": "center"
    },
    "text-right": {
      "textAlign": "right"
    },
    "font-bold": {
      "fontWeight": "700"
    },
    "font-medium": {
      "fontWeight": "500"
    },
    "uppercase": {
      "textTransform": "uppercase"
    },
    "capitalize": {
      "textTransform": "capitalize"
    },
    "text-slate-200": {
      "color": "#e2e8f0"
    },
    "text-slate-400": {
      "color": "#94a3b8"
    },
    "text-black": {
      "color": "#000"
    },
    "text-slate-100": {
      "color": "#f1f5f9"
    },
    "text-purple-600": {
      "color": "#9333ea"
    },
    "text-slate-900": {
      "color": "#0f172a"
    },
    "text-white": {
      "color": "#fff"
    },
    "text-green-300": {
      "color": "#86efac"
    },
    "text-red-500": {
      "color": "#ef4444"
    },
    "text-rose-700": {
      "color": "#be123c"
    },
    "text-rose-500": {
      "color": "#f43f5e"
    },
    "text-slate-300": {
      "color": "#cbd5e1"
    },
    "text-2xl": {
      "fontSize": 24,
      "lineHeight": 32
    },
    "text-xl": {
      "fontSize": 20,
      "lineHeight": 28
    },
    "text-sm": {
      "fontSize": 14,
      "lineHeight": 20
    },
    "text-lg": {
      "fontSize": 18,
      "lineHeight": 28
    },
    "hover:bg-red-400": {
      "backgroundColor": "#f87171"
    },
    "shadow-sm@3": {
      "elevation": 1.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-sm@4": {
      "shadowOffset": {
        "width": 0,
        "height": 1
      },
      "shadowRadius": 2,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-sm@5": {
      "shadowOffset": {
        "width": 0,
        "height": 1
      },
      "shadowRadius": 2,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-sm@6": {
      "elevation": 1.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-sm@7": {
      "shadowOffset": {
        "width": 0,
        "height": 1
      },
      "shadowRadius": 2,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-sm@8": {
      "shadowOffset": {
        "width": 0,
        "height": 1
      },
      "shadowRadius": 2,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-sm@9": {
      "elevation": 1.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-sm@10": {
      "shadowOffset": {
        "width": 0,
        "height": 1
      },
      "shadowRadius": 2,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-sm@11": {
      "shadowOffset": {
        "width": 0,
        "height": 1
      },
      "shadowRadius": 2,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-sm@12": {
      "elevation": 1.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-sm@13": {
      "shadowOffset": {
        "width": 0,
        "height": 1
      },
      "shadowRadius": 2,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-sm@14": {
      "shadowOffset": {
        "width": 0,
        "height": 1
      },
      "shadowRadius": 2,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "bg-green-600": {
      "backgroundColor": "#16a34a"
    },
    "shadow-sm@15": {
      "elevation": 1.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-sm@16": {
      "shadowOffset": {
        "width": 0,
        "height": 1
      },
      "shadowRadius": 2,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-sm@17": {
      "shadowOffset": {
        "width": 0,
        "height": 1
      },
      "shadowRadius": 2,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-sm@18": {
      "elevation": 1.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-sm@19": {
      "shadowOffset": {
        "width": 0,
        "height": 1
      },
      "shadowRadius": 2,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-sm@20": {
      "shadowOffset": {
        "width": 0,
        "height": 1
      },
      "shadowRadius": 2,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-sm@21": {
      "elevation": 1.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-sm@22": {
      "shadowOffset": {
        "width": 0,
        "height": 1
      },
      "shadowRadius": 2,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-sm@23": {
      "shadowOffset": {
        "width": 0,
        "height": 1
      },
      "shadowRadius": 2,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    }
  },
  atRules: {
    "shadow-sm": [[["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]]]
  },
  masks: {
    "hover:bg-red-400": 256
  }
});